feat(web): optimize the state of app
labring/laf pull request #1403
Opened 2023-07-14 03:45 UTC by imyuanx

optimize the state of app when I control app to start or restarting or stop.

## Before

![laf-before](https://github.com/labring/laf/assets/50652358/eba8187e-1559-4677-a33b-70bc63b60455)

## After
![laf-after](https://github.com/labring/laf/assets/50652358/03c0ad37-f479-4c98-a622-c04fe12854af)

2023-07-14 07:43 UTC, 0fatal commented
the "phase" field can only be used by backend, try another method:

Pause the application and poll the backend api to request the app state

2023-07-14 07:45 UTC, 0fatal requested changes
add "cursor-pointer" to the icon, don't add to CopyText directly

2023-07-14 10:22 UTC, imyuanx commented
> add "cursor-pointer" to the icon, don't add to CopyText directly

This PR is about app state

2023-07-17 03:34 UTC, newfish-cmyk requested changes

2023-07-17 03:34 UTC, newfish-cmyk commented on web/src/constants/index.ts
> +  Starting = "Starting",
remove

2023-07-17 03:34 UTC, newfish-cmyk commented on web/src/pages/home/mods/List/index.tsx
> +                                ? APP_STATUS.Starting
use "APP_PHASE_STATUS" instead

2023-07-17 03:34 UTC, newfish-cmyk commented on web/src/pages/home/index.tsx
> +    const newappListQueryData = appListQuery.data?.data.map((item: TApplicationItem) => {
newAppListQueryData

2023-07-17 05:28 UTC, imyuanx commented
Done

2023-07-17 05:42 UTC, newfish-cmyk approved these changes

2023-07-17 12:28 UTC, 0fatal approved these changes

2023-07-18 04:26 UTC, merged