feat(web): support resource monitor
labring/laf pull request #1471
Opened 2023-08-15 09:54 UTC by newfish-cmyk

2023-08-18 10:30 UTC, 0fatal requested changes

2023-08-18 10:30 UTC, 0fatal commented on web/src/pages/app/setting/AppMonitor/index.tsx
> +          unit=" MB"
MB

2023-08-18 10:30 UTC, 0fatal commented on web/src/pages/app/setting/AppMonitor/AreaCard/index.tsx
> +            value: Number(item[1]) / 1024 / 1024,
Number(item[1]) / 1024 / 1024 还是  Number(item[1])？

2023-08-18 10:30 UTC, 0fatal commented on web/src/pages/app/mods/StatusBar/MonitorBar/index.tsx
> -    { label: `CPU`, percent: cpuUsagePercent, color: "[#47C8BF]" },
* 100写在上面

2023-08-18 10:30 UTC, 0fatal commented on web/src/pages/app/setting/AppMonitor/PieCard/index.tsx
> +  const pieData = [
useMemo

2023-08-21 09:36 UTC, 0fatal approved these changes

2023-08-22 07:26 UTC, maslow approved these changes

2023-08-22 07:26 UTC, merged