feat(web): add function editor with lsp
labring/laf pull request #1627
Opened 2023-10-31 09:12 UTC by newfish-cmyk

2023-10-31 09:49 UTC, 0fatal requested changes

2023-10-31 09:49 UTC, 0fatal commented on web/src/pages/functionTemplate/Mods/MonacoEditor/index.tsx
> +                foreground: "65737e",
#65737e

2023-10-31 09:49 UTC, 0fatal commented on web/src/pages/app/mods/StatusBar/LSPBar/index.tsx
> +  const hostname = "scm3dt.100.66.76.85.nip.io";
hostname

2023-10-31 09:49 UTC, 0fatal commented on web/src/pages/app/functions/mods/FunctionPanel/index.tsx
> +
delete

2023-10-31 09:49 UTC, 0fatal commented on web/src/components/TextButton/index.tsx
> +      className={className + " !text-[#219BF4]"}
clsx

2023-10-31 09:49 UTC, 0fatal commented on web/src/components/Editor/userWorker.ts
> +// monaco.languages.typescript.typescriptDefaults.setEagerModelSync(true);
remove

2023-10-31 09:49 UTC, 0fatal commented on web/src/components/Editor/userWorker.ts
> +// import * as monaco from 'monaco-editor';
remove

2023-10-31 09:49 UTC, 0fatal commented on web/src/components/Editor/theme/index.js
> +  publisher: "vscode",
publisher

2023-10-31 09:49 UTC, 0fatal commented on web/src/components/Editor/TextModel.tsx
> +  const functionName = model.uri.path.match(/\/functions\/([^\.]+)\.ts/)[1];
lint

2023-10-31 09:49 UTC, 0fatal commented on web/src/components/Editor/LanguageClient.ts
> +      // debugLogging: true,
remove

2023-10-31 09:49 UTC, 0fatal commented on web/src/components/Editor/LanguageClient.ts
> +export type ExampleJsonEditor = {
remove

2023-10-31 09:49 UTC, 0fatal commented on web/src/components/Editor/LanguageClient.ts
> +    await languageClient.start();
remove await

2023-10-31 09:49 UTC, 0fatal commented on web/src/components/Editor/LanguageClient.ts
> +  secure?: boolean,
secure?: boolean = window.isSecureContext

2023-10-31 09:49 UTC, 0fatal commented on web/src/components/Editor/LanguageClient.ts
> +    // create a language client connection from the JSON RPC connection on demand
remove

2023-10-31 09:49 UTC, 0fatal commented on web/src/components/Editor/LanguageClient.ts
> +    name: "Sample Language Client",
Laf Language Client

2023-10-31 09:49 UTC, 0fatal commented on web/src/components/Editor/FunctionEditor.tsx
> +  const hostname = "scm3dt.100.66.76.85.nip.io";
hostname

2023-10-31 09:49 UTC, 0fatal commented on web/src/components/Editor/FunctionEditor.tsx
> +  });
, []

2023-10-31 09:49 UTC, 0fatal commented on web/src/components/Editor/FunctionEditor.tsx
> +      const start = async () => {
remove start wrap

2023-10-31 09:49 UTC, 0fatal commented on web/src/components/Editor/FunctionEditor.tsx
> +    allFunctionList.forEach(async (item: any) => {
remove async, change any

2023-10-31 09:49 UTC, 0fatal commented on web/src/components/Editor/FunctionEditor.tsx
> +    functionList.forEach(async (item: any) => {
remove async, change any

2023-11-01 03:46 UTC, 0fatal requested changes

2023-11-01 03:46 UTC, 0fatal commented on web/src/components/Editor/FunctionEditor.tsx
>  // import "./theme"
remove

2023-11-01 03:46 UTC, 0fatal commented on web/src/components/Editor/FunctionEditor.tsx
> +    const url = useMemo(() => createUrl(hostname, 80, "/_/lsp"), [hostname]);
remove 80

2023-11-01 03:46 UTC, 0fatal commented on web/src/components/Editor/TextModel.tsx
> +  const functionName = model.uri.path.match(/\/functions\/([^.]+)\.ts/)[1];
\.

2023-11-01 08:35 UTC, 0fatal approved these changes

2023-11-01 09:31 UTC, maslow approved these changes

2023-11-01 09:31 UTC, merged