feat(gateway): impl gateway crd and opt route&domain crd
labring/laf pull request #313
Opened 2022-09-08 16:58 UTC by skyoct

1. 重新定义gateway crd 和 domain crd
2. 实现gateway controller
3. route crd&controller适配gatway controller

remark：代码还未测试，可以先看一下思路

2022-09-09 02:34 UTC, maslow requested changes

2022-09-09 02:34 UTC, maslow commented on controllers/gateway/api/v1/gateway_types.go
> +	AppRoute *GatewayRoute `json:"appRoute,omitempty"`
route / domain 应该是由 gateway 根据条件匹配出来的， 是否应该放到 gateway status 里面，而不是 gateway spec 中？

2022-09-09 04:31 UTC, skyoct commented on controllers/gateway/api/v1/gateway_types.go
> +	AppRoute *GatewayRoute `json:"appRoute,omitempty"`
@maslow 这个是在gatway status里面写的
![image](https://user-images.githubusercontent.com/24541857/189272331-f4b1640d-c84f-411e-b4e9-8d977697547b.png)

2022-09-09 04:37 UTC, maslow commented on controllers/gateway/api/v1/gateway_types.go
> +	AppRoute *GatewayRoute `json:"appRoute,omitempty"`
👌 看错了

2022-09-15 11:45 UTC, maslow approved these changes

2022-09-15 11:46 UTC, merged