feat(cli): init cli
labring/laf pull request #488
Opened 2022-12-06 13:49 UTC by skyoct

初始化cli项目
实现应用列表&初始化应用

2022-12-07 02:28 UTC, maslow requested changes

2022-12-07 09:23 UTC, skyoct commented on cli/src/utils/request.ts
> +    error.data.msg = '服务器异常，请联系管理员！'
好的

2022-12-07 09:23 UTC, skyoct commented on cli/src/templates/application.ts
> +export interface ApplicationMetadata {
这不是返回数据的interface，是 配置文件模版

2022-12-07 15:56 UTC, LeezQ commented on cli/package.json
> +    "@types/cli-table2": "^0.2.3",
@types/cli-table: '^0.3.1'  ?

2022-12-07 16:25 UTC, LeezQ commented on cli/src/utils/request.ts
> +import { getAccessToken } from './token'
combine into one line

2022-12-07 16:27 UTC, LeezQ commented on cli/src/utils/token.ts
> +  return 'http://localhost:3000'
这些是不是应该弄到配置文件？

2022-12-24 23:55 UTC, maslow approved these changes

2022-12-24 23:56 UTC, merged