feat(web):  fix create & delete  collection bug
labring/laf pull request #659
Opened 2023-01-19 12:53 UTC by kongwy229

2023-01-19 13:12 UTC, LeezQ commented on web/src/pages/app/storages/mods/DeleteBucketModal/index.tsx
> +            {t("Delete")} {t("StoragePanel.Storage")}
这里也是，直接一个词就好了，不用拆成两个。

2023-01-19 13:16 UTC, LeezQ requested changes

2023-01-19 13:16 UTC, LeezQ commented on web/src/pages/app/storages/service.ts
> +          store.setCurrentStorage(data.data);
这里是用的 mutation 返回的，但是初始化的时候，用的是 query 列表里的，这里面的数据可能是不一样的。

2023-01-19 13:16 UTC, LeezQ commented on web/src/pages/app/storages/mods/CreateBucketModal/index.tsx
> +              <FormControl isRequired>
isInvalid={!!errors?.name} 要保留的。

2023-01-19 14:38 UTC, maslow submitted a review, later dismissed

2023-01-22 14:34 UTC, LeezQ approved these changes

2023-01-22 14:36 UTC, LeezQ approved these changes

2023-01-22 14:36 UTC, merged