fix(web): fix database page bugs & add storage refresh & reverse log
labring/laf pull request #761
Opened 2023-02-09 11:39 UTC by kongwy229

1. fix database page bugs
2. add storage refresh
3. limit the name of collection
4. reverse log
5. translate tags placeholder

2023-02-09 11:43 UTC, kongwy229 commented on web/src/pages/app/database/CollectionDataList/mods/DataPanel/index.tsx
> +  }, [entryDataQuery?.data?.list, setCurrentData, setRecord]);
@LeezQ  功能是可用的，但是依赖还没有处理好

2023-02-10 02:40 UTC, LeezQ requested changes

2023-02-10 02:40 UTC, LeezQ commented on web/src/pages/app/database/mods/AddDataModal/index.tsx
> +  }, [schema, setTemplate]);
这个 useEffect 应该没必要

2023-02-10 02:40 UTC, LeezQ commented on web/src/pages/app/database/service.ts
> +
这里的 Promise.resolve 有什么用吗？

2023-02-10 02:40 UTC, LeezQ commented on web/src/pages/app/database/service.ts
> +          // globalStore.showError(data.error);
这里注释了的话，这个 if 判断就没内容了。要么改成 if (!data.error)

2023-02-10 02:40 UTC, LeezQ commented on web/src/pages/app/functions/mods/BottomPanel/index.tsx
> +          NPM {t("FunctionPanel.Dependence")}
这个「 npm 」也可以一起放进去。用一个字段就好了。

2023-02-10 02:40 UTC, LeezQ commented on web/src/pages/app/storages/mods/UploadButton/index.tsx
>                (uploadType === "file" ? t("StoragePanel.File") : t("StoragePanel.Folder"))}
我觉得完整语句放一起比较好，不用单独拆成两个： (uploadType === "file" ? t("StoragePanel.UploadFile") : t("StoragePanel.UploadFolder"))}

2023-02-10 02:40 UTC, LeezQ commented on web/src/components/Pagination/index.tsx
> +
这里的代码感觉有问题，
1. maxPage, onChange, page, values 都是 props 或者计算得到的值，不需要 useEffect
2. 判断之后都是运行
```
onChange({
        ...values,
        page: 1,
      });
```
那只要计算得到 page 值就行了。

2023-02-10 03:10 UTC, kongwy229 commented on web/src/pages/app/database/mods/AddDataModal/index.tsx
> +  }, [schema, setTemplate]);
这里如果不使用useEffect ,每次都setTemplate，就会一直重新渲染，导致死循环

2023-02-10 06:21 UTC, LeezQ requested changes

2023-02-10 06:21 UTC, LeezQ commented on web/src/pages/app/database/mods/AddDataModal/index.tsx
> +  }, [schema, setTemplate]);
不用 setTemplate 啊。可以在这里直接默认值：
const keys = Object.keys(schema).filter((key) => key !== "_id");
    const newTemplate: { [key: string]: any } = {};
    for (let key of keys) {
      newTemplate[key] = "";
    }
const [template, setTemplate] = useState(newTemplate);

2023-02-10 07:53 UTC, LeezQ approved these changes

2023-02-10 07:54 UTC, merged