fix(web) : fix range of edit and delete buttons
labring/laf pull request #804
Opened 2023-02-18 05:21 UTC by zuoFeng59556

![fd15ecc8089e583dd41abf2b22c8812](https://user-images.githubusercontent.com/82700206/219842671-3ea3ea38-2000-45c3-843c-db2e5a225e51.png)

2023-02-18 14:24 UTC, LeezQ requested changes

2023-02-18 14:24 UTC, LeezQ commented on web/src/pages/home/mods/List/index.tsx
> +                        <MenuItem minH="40px" display={"block"} padding={"0"}>
有没有通用的方式，现在这种每次都要在 MenuItem 加这个样式吗？

2023-02-19 03:23 UTC, zuoFeng59556 commented on web/src/pages/home/mods/List/index.tsx
> +                        <MenuItem minH="40px" display={"block"} padding={"0"}>
我现在换了一种方式，你看看行不

2023-02-20 02:29 UTC, LeezQ approved these changes

2023-02-20 02:29 UTC, merged