Backup
labring/laf pull request #845
Opened 2023-03-03 03:54 UTC by zimtsui

2023-03-08 06:18 UTC, skyoct commented
@zimtsui Have you finished already?

2023-03-18 21:03 UTC, maslow requested changes

2023-03-18 21:03 UTC, maslow commented on server/src/backup/backup.controller.ts
> +		const dbUri = this.dbService.getConnectionUri(region, database);
应该是要使用统一的、专用的备份账户，这里只需要把 database name 传过去即可，不需要 app db uri。
并且，app db uri 也没有 dump / relay binlog 的权限。

2023-03-18 21:03 UTC, maslow commented on server/src/backup/dto/submit-restore.dto.ts
> +				},
缩进。

2023-03-18 21:03 UTC, maslow commented on packages/node-json-rpc/package.json
这个包有无介绍，至少简介用途。

2023-03-18 21:03 UTC, maslow commented on packages/mongo-async-rpc/package.json
这个包有无介绍，至少简介用途。

2023-03-19 08:46 UTC, maslow requested changes

2023-03-19 08:46 UTC, maslow commented on packages/mongo-async-rpc/package.json
> +    "@zimtsui/pollerloop": "^0.0.5"
这些包是？  是否隐藏了一些逻辑，或者封装了非通用惯例的用法？

2023-05-17 18:15 UTC, closed without merging